openapi: 3.0.0
info:
  title: PingOne Platform API - Agreement Management
  description: The PingOne Platform API covering the PingOne Agreement Management service
  version: '2023-06-29'
servers:
  - url: '{protocol}://{baseDomain}.{suffix}'
    description: PingOne Platform API Endpoint
    variables:
      suffix:
        enum:
          - 'eu'
          - 'com'
          - 'asia'
          - 'ca'
        default: 'com'
      baseDomain:
        default: 'agreement-mgmt.pingone'
      protocol:
        default: 'https'
  - url: '{protocol}://{baseHostname}'
    description: PingOne Platform API Endpoint
    variables:
      baseHostname:
        default: 'agreement-mgmt.pingone.com'
      protocol:
        default: 'https'
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth bearer token (see documentation)
  schemas:
    AgreementRevisionText:
      type: object
      properties:
        resourcePath:
          type: string
        data:
          type: string
        dataType:
          type: string
    P1Error:
      type: object
      properties: 
        id:
          description: A unique identifier that is stored in log files and always included in an error response. This value can be used to track the error received by the client, with server-side activity included for troubleshooting purposes.
          type: string
        code:
          description: A general fault code which the client must handle to provide all exception handling routines and to localize messages for users. This code is common across all PingOne services and is human readable (such as a defined constant rather than a number).
          type: string
        message:
          description: A short description of the error. This message is intended to assist with debugging and is returned in English only.
          type: string
        details:
          description: Additional details about the error. Optional information to help resolve the error and to display to users.
          type: array
          items:
            type: object
            properties:
              code:
                description: A general fault code which the client must handle to provide all exception handling routines and to localize messages for users. This code is common across all PingOne services and is human readable (such as a defined constant rather than a number).
                type: string
              target:
                description: The item that caused the error (such as a form field ID or an attribute inside a JSON object).
                type: string
              message:
                description: A short description of the error. This message is intended to assist with debugging and is returned in English only.
                type: string
              innerError:
                description: Additional details to help the client developer resolve the fault (primarily for UI validation reasons).
                type: object
                properties:
                  rangeMinimumValue:
                    description: Errors that failed due to range violation. This attribute represents the minimum value of the range.
                    type: integer
                  rangeMaximumValue:
                    description: The maximum range or value of an attribute.
                    type: integer
                  allowedPattern:
                    description: A regex pattern describing an acceptable input pattern.
                    type: string
                  allowedValues:
                    description: A list describing acceptable values.
                    type: array
                    items:
                      type: string
                  maximumValue:
                    description: The maximum value allowed for the request.
                    type: integer
                  referencedValues:
                    type: array
                    items:
                      type: string
  responses:
    '400':
      description: Invalid request received.  Malformed JSON, malformed HTTP request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '401':
      description: Request failed due to authorization issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '403':
      description: Request failed due to authorization issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '404':
      description: Not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '405':
      description: Invalid request received.  Malformed JSON, malformed HTTP request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '409':
      description: Conflict.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '429':
      description: Request was rate limited
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
    '500':
      description: Uncaught error occurred.  Platform outage
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
security:
  - bearer: []
tags:
  - name: Agreement Revisions Resources
paths:
  /environments/{environmentID}/agreements/{agreementID}/languages/{languageID}/revisions/{revisionID}.json:
    get:
      tags:
        - Agreement Revisions Resources
      summary: READ One Agreement Language Revision
      operationId: readOneAgreementLanguageRevision
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: agreementID
          in: path
          schema:
            type: string
          required: true
        - name: languageID
          in: path
          schema:
            type: string
          required: true
        - name: revisionID
          in: path
          schema:
            type: string
          required: true
      responses:
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          $ref: '#/components/responses/409'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgreementRevisionText'
